### ISSUE TITLE
'could not load cache' when building llvm-mctoll

### ISSUE THREAD

**Issue by Brubbish** [microsoft/llvm-mctoll#137]
I am new in llvm and cmake, so the issue might a bit shallow
I've already processed 4 steps in 'Building as part of the LLVM tree' in README. I stuck in step 5 when I use ` cmake --build ../../mctoll-build/ -- llvm-mctoll`  and it occurred an `Error: could not load cache`.
![image](https://user-images.githubusercontent.com/29673689/132988752-0fb2041c-eb4d-4a70-87ce-876338c13737.png)

my OS is Ubuntu20.04

**Comment by bharadwajy** [comment]
Thanks for your interest in the project.

A couple of potential things to verify:
1. Check disk space availability.
2. Ensure your source directory structure is as expected i.e., `llvm-mctoll` directory is in `llvm-project/llvm/tools` directory.
3. Follow the steps in [README.md](https://github.com/microsoft/llvm-mctoll/blob/master/README.md) verbatim, if you are new to LLVM ecosystem.

**Comment by Brubbish** [comment]
@bharadwajy Thanks a lot, I found I missed the step to put  `llvm-mctoll` dir in the right directory.

Also, if someone has a problem cloning llvm-project in Github due to GFW like me, tuna's llvm-project mirror is a smart choice.
If it occurs to have errors while executing `cmake --build ./ -- llvm-mctoll`, it is maybe because of your low ram.
