### ISSUE TITLE
Does Mctoll Translator support Weak Memory Model Architectures ?

### ISSUE THREAD

**Issue by hailongeric** [microsoft/llvm-mctoll#191]
Lasagne: A Static Binary Translator for Weak Memory Model Architectures (Rodrigo & Dennis 2022)
This article shows they perform the fence insertion in WMM and most of their contributions have already been
accepted and incorporated in the main mctoll repository. 
So I want to know whether mctoll uses the lasagne LIMM fence insertion. And Whether Mctoll contains Lasagne's fence insertion code or not. And is their contribution only SEE support?

**Comment by bharadwajy** [comment]
> So I want to know whether mctoll uses the lasagne LIMM fence insertion. And Whether Mctoll contains Lasagne's fence insertion code or not. 

No.

> And is their contribution only SEE support?

Yes.
