### ISSUE TITLE
Raising strings 

### ISSUE THREAD

**Issue by deXetrous** [microsoft/llvm-mctoll#21]
I generated a binary for a C code that involved char * and an assignment to it. When raised using llvm-mctoll, the string constant is not found as a global string and neither the IR has any variables of type i8*. All the variables present are either i64 or i32. Please let me know if this is a bug or the support for it is not yet added.

**Comment by bharadwajy** [comment]
Thanks for the report. This is a known limitation.

Work is ongoing to identify memory accesses and the types of accessed data to abstract them as LLVM variables as appropriate.

**Comment by aaronsm** [comment]
Strings are supported now. If you are still having problems let us know.

$ cat string.c

#include <stdio.h>
char str1[]="my string";
int main() {
  printf("%s\n", str1);
}

$ gcc -O2 string.c
$ ./a.out
my string
$ llvm-mctoll a.out
cat a.out-dis.ll

; ModuleID = 'a.out'
source_filename = "a.out"

@RO-String = private constant [10 x i8] c"my string\00", align 1

define dso_local void @main() {
entry:
  %0 = bitcast [10 x i8]* @RO-String to i8*
  %1 = tail call i32 @puts(i8* %0)
  ret void
}

declare dso_local i32 @puts(i8*)
