### ISSUE TITLE
Test suite failures

### ISSUE THREAD

**Issue by woachk** [Microsoft/llvm-mctoll#23]
llvm-mctoll/X86/X86ModuleRaiser.cpp:66: virtual bool X86ModuleRaiser::collectDynamicRelocations(): Assertion `(DotRelaDotPltShdr.get()->sh_info == DotGotDotPltSec.getIndex()) && ".rela.plt does not refer .got.plt section"' failed when trying to run even the test suite. Ubuntu 18.04 on the Windows Subsystem for Linux.

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"

**Comment by bharadwajy** [comment]
Thanks for the report.

The tool has not been tested on Ubuntu running on WSL. We would really appreciate any help with a patch addressing the failure reported.

**Comment by bharadwajy** [comment]
Please reopen, if you have additional info.
