### ISSUE TITLE
Build error after API change

### ISSUE THREAD

**Issue by plowsec** [Microsoft/llvm-mctoll#24]
Hi guys,

Just wanted to notify you that a (minor) build error happens with latest versions of LLVM/Clang:
`llvm-mctoll/src/llvm/tools/llvm-mctoll/MachODump.cpp:6832:65: error: no matching function... « llvm::DIContext::getLineInfoForAddress(uint64_t&) `

Kind regards,
plowsec

**Comment by bharadwajy** [comment]
Thanks for the report.

Fix (4a48e33916f15e1741f4313a70806ebebbba5806) pushed.

Reopen if you still see the problem.
