### ISSUE TITLE
IDA-Pro

### ISSUE THREAD

**Issue by weiwang999** [Microsoft/llvm-mctoll#25]
I have no idea of where I can download this decompiler. it seems like it is not free

**Comment by bharadwajy** [comment]
Hello! Can you add more detail about what you are asking about? This open source project that raises (decompiles) binaries to LLVM IR is in no way dependent on IDA-Pro. This tool only depends on LLVM inftrastructure.

If you are interested in building this tool, please follow the steps listed in the README.md.

Hope that helps!

**Comment by bharadwajy** [comment]
Please reopen, if you have additional info.
