### ISSUE TITLE
Building Integration Tests

### ISSUE THREAD

**Issue by weiwang999** [Microsoft/llvm-mctoll#26]
The test_suite directory is automatically generated!

All modifications should happen to test_suite_generator

I don't know what does this mean and I failed to find this directory test_suit_generator.
How is it be generated automatically?

**Comment by bharadwajy** [comment]
I do not recognize the directory you refer to in the context of this project.

Can you please provide steps to demonstrate what you are talking about? That would help addressing any questions or concerns you have.

Thanks!

**Comment by bharadwajy** [comment]
Please reopen, if you have additional info.
