### ISSUE TITLE
llvm 9.0 doesn't have setCategory function?

### ISSUE THREAD

**Issue by bin2415** [microsoft/llvm-mctoll#27]
I build this project with latest llvm/clang(9.0) and it has an error:

```
class llvm::cl::Option has no member named setCategory
```

in file [link](https://github.com/microsoft/llvm-mctoll/blob/master/llvm-mctoll.cpp#L1768)

And I checked the source code of the llvm 9.0, and find there is a function named addCategory instead([link](https://llvm.org/doxygen/classllvm_1_1cl_1_1Option.html#a38b105735277855bf675dcd5009a975a)). So I replace the setCategory with addCategory, and it worked.

**Comment by bharadwajy** [comment]
Thanks for your interest in the project.

Yes, we are aware of this recent API change in LLVM.

Please note that the sources of llvm-mctoll are known to build and run using the repo tips noted in LLVMVersion.txt located in the top-level directory.

This change will be pushed along with an update to LLVMVersion.txt as well
