### ISSUE TITLE
when make occurs errors

### ISSUE THREAD

**Issue by chlizheng** [Microsoft/llvm-mctoll#3]
Hi.
I tried to build the tool to translate arm to llvm-ir. But when I run the sixth step "make llvm-mctoll" it cause errors as following:
     "collect:2  errror: ld returned 1 exit status
      make[2]: *** [bin/llvm-mctoll] error  1
      make[1]: ***[tools/llvm-mctoll/CMakeFiles/llvm-mctoll.dir/all] error 2
      make : ***[all] error 2
"
I don't know where is the problem. Could you give me some suggestions?
best regards

**Comment by bharadwajy** [comment]
Thanks for your interest in the tool.

Can you please run the command 'make VERBOSE=1 llvm-mctoll' to get additional details of the failure and share them?

Please let me know of the OS and version on which you are attempting the build.

I expect the tool build and tests to pass on Ubuntu 16.xx, 17.xx and 18.xx.

Thanks!

**Comment by chlizheng** [comment]
@bharadwajy 
Thanks, I run 'make VERBOSE=1 llvm-mctoll' but I didn't find more details and my Os is Ubantu-14.04. 

And I want  to translate arm assembly code to llvm-ir staticly for a try by translating simple code. In my opinion, I should translate arm instruction to llvm-ir one by one, and then replace arm instructions by a script.  Maybe I think it too simple.

But I didn't find enough data to do this. It seems that the instructions about jump is difficult and the list of AMT is too large.  What's more, I'm not sure how to translate some arm instructions to llvm-ir,  and how to design whole infrastructure of target .ll file just according to assembly code?

Do you have some reference data  about the  translation job? And could you give me some references?
best regards.

**Comment by bharadwajy** [comment]
As noted in README.md, at present development and testing is being done using Ubuntu 18.04. It is expected that build and test would work on Ubuntu 16.04, 17.04 and 17.10.

Support for codegen and/or ELF binary packaging differences on Ubuntu 14.04 needs to be added.
