### ISSUE TITLE
external functions

### ISSUE THREAD

**Issue by Trass3r** [microsoft/llvm-mctoll#33]
For C++ code the most important change is probably:

```diff
diff --git a/ExternalFunctions.cpp b/ExternalFunctions.cpp
index 9bdf6fb..8cfcd8c 100644
--- a/ExternalFunctions.cpp
+++ b/ExternalFunctions.cpp
@@ -29,7 +29,10 @@ const std::map<StringRef, ExternalFunctions::RetAndArgs>
         {"puts", {"i32", {"i8*"}, false}},
         {"free", {"void", {"i8*"}, false}},
         {"atoi", {"i32", {"i8*"}, false}},
-        {"exit", {"void", {"i32"}, false}}};
+        {"exit", {"void", {"i32"}, false}},
+        {"_Znwm", {"i8*", {"i64"}, false}}, // new
+        {"_ZdlPv", {"void", {"i8*"}, false}} // delete
+        };
 
 // Construct and return a Function* corresponding to a known external function
 Function *ExternalFunctions::Create(StringRef &CFuncName, ModuleRaiser &MR) {
```

I'd suggest to add that for the time being.

But in general that approach does not scale of course (different compilers, name mangling, calling conventions, architecture, missing llvm attributes, parameter names, ...).
I've seen it before in fcd. Then they switched to parsing a header file with libclang, which is better but pulls in the whole clang dependency.
I imagine relying on a separately generated bitcode file with all the declarations like `declare i8* @_ZdlPv(i64 size)` could be a clean solution.

**Comment by bharadwajy** [comment]
> For C++ code the most important change is probably:
...
> But in general that approach does not scale of course (different compilers, name mangling, calling conventions, architecture, missing llvm attributes, parameter names, ...).
We have not yet started implementing support to raise C++ binaries. Maintaining a list of "known" C++ function prototypes as we currently to support raising of C binaries is not what I wish to do - primarily for the reasons spelt out by you. However, I would expect that "standard" name mangler/demanglers on Linux and Windows can get us to figure out the function prototypes of a large portion of C++ binaries. That would liberate us from the need to maintain a list of "known" function prototypes.

> I've seen it before in fcd. Then they switched to parsing a header file with libclang, which is better but pulls in the whole clang dependency.

Thanks for letting us know of this. 

> I imagine relying on a separately generated bitcode file with all the declarations like `declare i8* @_ZdlPv(i64 size)` could be a clean solution.

Plausible - but would, IMHO, definitely make the tool user's experience rather cumbersome. They would need to sift through the disassembly (or in some other way) to figure out the contents of such a file. I would very much like the tool usage experience to be as smooth as possible.

**Comment by Trass3r** [comment]
> Plausible - but would, IMHO, definitely make the tool user's experience rather cumbersome. They would need to sift through the disassembly (or in some other way) to figure out the contents of such a file. I would very much like the tool usage experience to be as smooth as possible.

The disassemblers/decompilers out there often have some kind of pre-generated function signature "libraries" and those work fine. You never touch the builtin ones as an end-user.

> bitcode file

It just occurred to me you could also use .ll files of course. Easier to edit for the user.

**Comment by Trass3r** [comment]
I thought of these library files as simply being generated with standard clang from some headers but overlooked that clang does not emit function declarations unless they are actually used.

**Comment by bharadwajy** [comment]
Prototypes of external function references are now obtained via libtooling-based support that was implemented.  This is expected to address the issue at hand.
