### ISSUE TITLE
Building llvm-mctoll on Windows

### ISSUE THREAD

**Issue by Necrolis** [microsoft/llvm-mctoll#37]
Following the discussion in #30 I though it best to open a new issue to discuss support for compiling and running on Windows. As well as support for the Windows PE/COFF format.

**Comment by Trass3r** [comment]
Maybe [that's](https://github.com/Trass3r/llvm-mctoll/commit/63bac590639e2f2b1ea59546dee54c2f5e80516c) a bit clearer.

**Comment by bharadwajy** [comment]
> Maybe [that's](https://github.com/microsoft/llvm-mctoll/compare/master...Trass3r:master#diff-04c6e90faac2675aa89e2176d2eec7d8) a bit clearer.
LGTM.

I'd add the corresponding Debug build command as well - just to eliminate any possible misconception that Release build is necessary to build llvm-mctoll.

@Necrolis Would you be able to verify the modified instructions are good to guide building on Windows?

**Comment by Trass3r** [comment]
https://github.com/Trass3r/llvm-mctoll#getting-started

**Comment by aaronsm** [comment]
Thanks for clarifying the build instructions!
