### ISSUE TITLE
SSE2

### ISSUE THREAD

**Issue by Trass3r** [microsoft/llvm-mctoll#40]
Really necessary since all x64 code is using SSE2 by default.
At least the move operations should be implemented for #39 and #38.

**Comment by haneefmubarak** [comment]
Hello!

@E-Ruhl and I are interested in helping to add SSE support to `mctoll`. Has any progress been made on this and if not what would the first steps be? We are happy to put in the time to get it to a workable state.

CC @bharadwajy

**Comment by bharadwajy** [comment]
Thanks for your interest and offer. Much appreciated.

I had pushed an initial implementation(7487a7a88dfb074543a10e8147c210ad3dfb7eeb) a while ago. That should at least provide a starting point to support SSE2 instruction translation/abstraction. Of course, the other equally important aspect to address is abstracting SSE2 registers used as function arguments.

Several x64 tests (https://github.com/microsoft/llvm-mctoll/tree/master/test) are compiled with `-mno-sse` flag. You can start by getting rid of that flag and add support to raise the resulting binaries that contain SSE2 instructions. Raising the binaries of https://github.com/microsoft/llvm-mctoll/tree/master/test/dhrystone built without `-mno-sse` would be a good first milestone.
