### ISSUE TITLE
can't build with BUILD_SHARED_LIBS=ON

### ISSUE THREAD

**Issue by Trass3r** [microsoft/llvm-mctoll#43]
```
undefined symbol: RaiserContext::ModuleRaiserRegistry
>>> referenced by X86ModuleRaiser.cpp:45
...
```
cause X86Raiser is then built as a shared lib, see https://github.com/llvm/llvm-project/blob/06f9ce84fe6/llvm/cmake/modules/AddLLVM.cmake#L680.

**Comment by Trass3r** [comment]
X86Raiser is easy to fix but not sure if you really have to spell out all the deps explicitly in the main file (shouldn't it pick at least some of them up as transitive deps?):
```diff
--- a/X86/CMakeLists.txt
+++ b/X86/CMakeLists.txt

-add_llvm_library(X86Raiser
+llvm_add_library(X86Raiser STATIC

--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -7,9 +7,17 @@ set(LLVM_MCTOLL_BINARY_DIR ${CMAKE_CURRENT_BINARY_DIR})
 
 llvm_map_components_to_libnames(llvm_libs
   ${LLVM_TARGETS_TO_BUILD}
+  Core
+  BitWriter
+  CodeGen
   DebugInfoDWARF
   DebugInfoPDB
+  Demangle
+  MC
+  MCDisassembler
+  Object
   Symbolize
+  Support
 )
```

**Comment by bharadwajy** [comment]
What is the rationale behind the desire/need to build with `BUILD_SHARED_LIBS=ON`? How do you envision LLVM built with this option to be used when building `llvm-mctoll`?

https://llvm.org/docs/CMake.html says
```
Note
BUILD_SHARED_LIBS is only recommended for use by LLVM developers. If you want to build LLVM as a shared library, you should use the LLVM_BUILD_LLVM_DYLIB option.
```

How would it help an `llvm-mctoll`developer?

**Comment by Trass3r** [comment]
As the docs explain I use it for development, speeds up incremental builds by reducing linker work.

**Comment by aaronsm** [comment]
Thanks for the patch!
