### ISSUE TITLE
DOC: LICENSE not mentioned in README.md

### ISSUE THREAD

**Issue by brute4s99** [Microsoft/llvm-mctoll#5]
There is no section specifying the license of LLVM_mctoll in [README.md](https://github.com/Microsoft/llvm-mctoll/blob/master/README.md)

**Comment by aaronsm** [comment]
The license is LLVM and in the license file. 
https://github.com/Microsoft/llvm-mctoll/blob/master/LICENSE

Or you can click the "View license" button on github to show the license. https://blog.github.com/2016-09-21-license-now-displayed-on-repository-overview/
