### ISSUE TITLE
Malformed LLVM module

### ISSUE THREAD

**Issue by tathanhdinh** [microsoft/llvm-mctoll#62]
Hello,

When raising an ELF generated with:

```c
// foo.c
struct Foo {
    struct Foo *next;
};

struct Foo* __attribute__ ((noinline)) foo(struct Foo *f) {
    while (f->next != 0) {
        f = f->next;
    }
    return f;
}

int main() {
    return foo(10);
}

// compile
gcc -O3 foo.c -o foo
```

and the CFG is something like this:
![foo](https://user-images.githubusercontent.com/79418/74196949-ae1d1600-4c5e-11ea-89d0-2c5ab5bddd3c.png)

I've got the following result

```llvm
define dso_local i64 @foo(i64 %arg1) {
entry:
  %0 = inttoptr i64 %arg1 to i64*
  %memload = load i64, i64* %0, align 8
  %1 = and i64 %memload, %memload
  %highbit = and i64 -9223372036854775808, %1
  %SF = icmp ne i64 %highbit, 0
  %ZF = icmp eq i64 %1, 0
  %CmpZF_JNE = icmp eq i1 %ZF, false
  br i1 %CmpZF_JNE, label %entry, label %bb.1     ; so it may branch to entry

bb.1:                                             ; preds = %entry
  ret i64 %arg1
}

define dso_local i64 @main() {
entry:
  %0 = zext i32 10 to i64
  %RAX = tail call i64 @foo(i64 %0)
  ret i64 %RAX
}
```
while I believe that the result of `@foo` is not correct (the loop cannot exit since `%memload` is always the same),  the module is not even "valid" LLVM because there is a branch to the entry block in `@foo`. 

A most naive fix that I can think of is to just create an empty entry block before the real one, like that:

```llvm
define dso_local i64 @foo(i64 %arg1) {
entry:
  br label %real_entry

real_entry:
  %0 = inttoptr i64 %arg1 to i64*
  %memload = load i64, i64* %0, align 8
  %1 = and i64 %memload, %memload
  %highbit = and i64 -9223372036854775808, %1
  %SF = icmp ne i64 %highbit, 0
  %ZF = icmp eq i64 %1, 0
  %CmpZF_JNE = icmp eq i1 %ZF, false
  br i1 %CmpZF_JNE, label %real_entry, label %bb.1

bb.1:                                             ; preds = %entry
  ret i64 %arg1
}
```

I'm still very new to the project, I don't know where should I start, may be in a "validation pass" which check whether there is a branch to the entry block?

Thanks in advance.

**Comment by bharadwajy** [comment]
Thanks for using the tool and for the bug report.

Can you add the gcc version, as well as the Linux distro used (may be the later is not entirely relevant, but please do so, if you can) to the details of this issue?

Using gcc 7.4.0 on Ubunbtu 18.04.04, following is the code generated for foo():

```
0000000000000610 <foo>:
 610:	48 89 f8             	mov    rax,rdi
 613:	eb 06                	jmp    61b <foo+0xb>
 615:	0f 1f 00             	nop    DWORD PTR [rax]
 618:	48 89 d0             	mov    rax,rdx
 61b:	48 8b 10             	mov    rdx,QWORD PTR [rax]
 61e:	48 85 d2             	test   rdx,rdx
 621:	75 f5                	jne    618 <foo+0x8>
 623:	f3 c3                	repz ret 
 625:	66 2e 0f 1f 84 00 00 	nop    WORD PTR cs:[rax+rax*1+0x0]
 62c:	00 00 00 
 62f:	90                   	nop
```

Unfortunately, the code generated with gcc 7.4.0 does not demonstrate the code pattern that triggers the malformed tool output reported in this issue. So, it would be very beneficial to get the gcc version that generates the code pattern triggering the failure, thus allowing for support to be added to correctly handle such a code pattern.

While the solution you propose seems reasonable, I would also like to look at the possibility of addressing it during BasicBlock creation.

Thanks!

**Comment by tathanhdinh** [comment]
Hello,
Thanks you for the response. My machine is Fedora 31

```bash
gcc --version
gcc (GCC) 9.2.1 20190827 (Red Hat 9.2.1-1)
```

**Comment by bharadwajy** [comment]
Thanks! Since I do not have immediate access to that version of gcc, can you please provide the assembly listing of `foo.c` generated on your machine using the above gcc version (`gcc -O3 -S foo.c` should generate `foo.s`)? This would help with creation of a test case as well as allow for implementing a fix.

Any help is highly appreciated.

**Comment by bharadwajy** [comment]
Fixed the syntax error in test provided and added to tool tests. Passes.
