### ISSUE TITLE
Incorrect LLVM IR of Array operation generated from this tool

### ISSUE THREAD

**Issue by leibo-hust** [microsoft/llvm-mctoll#69]
When I testing the correctness of this tool, I found the incorrect result of the generated IR and the output.

My source file is about the **operation of arrays** named c_test.c, as follow: 
#include <stdio.h>

int main()
{
	int arr[3] = {1, 2, 4};
	int mat[3][2] = {
			  1, 2,
			  3, 4,
			  5, 6
			};
	int result[2] = {0};
	int i = 0, j = 0;
	for(i = 0; i < 2; i++)
		for(j = 0; j < 3; j++) {
			result[i] += mat[j][i] * arr[j];
	}
    int k = 0;
	for(k = 0; k < 2; k++)
    {
        printf("%d\n", result[k]);
    }

	return 0;
}

Firstly, I use the command “clang c_test.c -o c_test.out” to generate the binary executable code, and run the "./c_test.out" shows the **right output**: 27 34.

Secondly, I use the llvm-mctoll to generate the IR of c_test.out by run the  command "llvm-mctoll -d c_test.out".

Then, I run the command "llc c_test.out-dis.ll -o c_test.out-dis.s" to generate the assembly code and use "clang c_test.out-dis.s -o c_test-dis.out" to generate  the fianl code. But the **result of c_test-dis.out** is: 21 and 21, which is incorrect. Thus, I want to know where is the problem and how to solve it.
Thanks a lot!

**Comment by bharadwajy** [comment]
Thanks for the report. I reproduced it. 

Currently abstraction of memory operand with sp/bp as base register and displacement (**no** index reg/scale) is implemented. Support for abstraction of memory opernad with sp/bp as base register, index reg/scale and displacement needs to be added to handle this binary.

**Comment by leibo-hust** [comment]
Thank u very much!!! 
Actually, I waited for your reply and answer  a long time, because the operation of the array is very important to me, and if you complete add added this, please notice me and that will help me a lot.
Thanks again and thanks for your reply and hard work!

**Comment by bharadwajy** [comment]
> Thank u very much!!!
> Actually, I waited for your reply and answer a long time, because the operation of the array is very important to me, and if you complete add added this, please notice me and that will help me a lot.
> Thanks again and thanks for your reply and hard work!

Thanks for your patience. I just pushed a fix.

Feel free to report any additional issues that you might find or improvements to the tool you might wish to suggest.

**Comment by bharadwajy** [comment]
A fix for this issue has been pushed.

Thanks.
________________________________

**Comment by leibo-hust** [comment]
Hi, I find another problem that's when the `array` is `float` or `double`, there are errors when using the `llvm-mctoll -d f.out` command.

**Comment by bharadwajy** [comment]
Please file a new issue with a reproducer.

Thanks.

**Comment by leibo-hust** [comment]
OK, but the code is almost the same with `c_test.c` that mentioned above, I only changed the array type to floatint and double.
