### ISSUE TITLE
Unsupported undefined function

### ISSUE THREAD

**Issue by leibo-hust** [microsoft/llvm-mctoll#72]
When I uset llvm-mctoll to translate the .out file to the .bc, I met the error: **`Unsupported undefined function`**.

The source code of my program is:
#include <stdio.h>
#include <stdlib.h>

```
int main()
{
        int i;
        i = rand() % 11;
        printf("%d\n", i);
}
```

because there is function rand, so I defined the rand.txt as:
```
;include `int rand(void)` defined in rand.out
include-functions {
  rand.out:i32 rand(void)
}
```
when I use the command "llvm-mctoll -d --filter-functions-file=rand.txt rand.out", the error occured. And I don't know if I'm doing it right. Thanks a lot!

**Comment by bharadwajy** [comment]
Thanks for your report.

`int rand()` is an external function and does not have an implementation in the binary being raised. The command-line option `--filter-functions-file` is used to include/exclude prototypes of functions implemented in the binary being raised. So, using the filtering functionality would not address the issue reported here.  

You are seeing this issue because the function prototype of `rand()` is not listed in  `[ExternalFunctions.cpp](https://github.com/microsoft/llvm-mctoll/blob/master/ExternalFunctions.cpp)` and hence is not (yet) known to the tool. You should be able to raise the binary of the source provided in this issue by applying the following patch to your local repo :

```
diff --git a/ExternalFunctions.cpp b/ExternalFunctions.cpp
index 13e73a9..4e2bc50 100644
--- a/ExternalFunctions.cpp
+++ b/ExternalFunctions.cpp
@@ -36,6 +36,7 @@ const std::map<StringRef, ExternalFunctions::RetAndArgs>
         {"printf", {"i32", {"i8*"}, true}},
         {"putchar", {"i32", {"i32"}, false}},
         {"puts", {"i32", {"i8*"}, false}},
+        {"rand", {"i32", {}, false}},
         {"realloc", {"i8*", {"i8*", "i64"}, false}},
         {"round", {"float", {"float"}, false}},
         {"sleep", {"i32", {"i32"}, false}},
```

**Comment by leibo-hust** [comment]
Thank you very much for your answers, which really solved my confusions. I also want to know where can I see the `complete list of external functions`? This allows me to know which functions are available and which are not. thank you very much!

**Comment by bharadwajy** [comment]
> Thank you very much for your answers, which really solved my confusions. I also want to know where can I see the **complete list of external functions**? This allows me to know which functions are available and which are not. thank you very much!

As noted in my earlier reply, the complete list of function prototypes considered external by llvm-mctoll, is in [ExternalFunctions.cpp](https://github.com/microsoft/llvm-mctoll/blob/master/ExternalFunctions.cpp). You can modify that file in your local copy of llvm-mctoll repo to add the prototype of any **externally linked** function that your binary is linked to, using the appropriate syntax, if it does not feature in that list, as demonstrated by the patch that adds `rand()` in my earlier reply, and rebuild llvm-mctoll.

Hope that helps.

**Comment by leibo-hust** [comment]
ok, got it, so it means that I can add the functions that I want by myself?

**Comment by bharadwajy** [comment]
> ok, got it, so it means that I can add the functions that I want by myself?

Yes.

**Comment by leibo-hust** [comment]
> > ok, got it, so it means that I can add the functions that I want by myself?
> 
> Yes.

that's really great!! and are there any guide on how to add the functions?thanks a lot

**Comment by leibo-hust** [comment]
for example, what should I do is just modify the content of `ExternalFunctions::GlibcFunctions`, such as:
 ExternalFunctions::GlibcFunctions = {
        {"_IO_putc", {"i32", {"i32", "i64"}, false}},
       ......
        {"time", {"i64", {"i64*"}, false}};
       **{"funciton_that__I_want", {“return type”}, {“parameter type”}, ?}}}**

**Comment by bharadwajy** [comment]
> > > ok, got it, so it means that I can add the functions that I want by myself?
> > 
> > 
> > Yes.
> 
> that's really great!! and are there any guide on how to add the functions?thanks a lot

Take a look at the existing array entries and `struct RetAndArgs_t` in [ExternalFunctions.h](https://github.com/microsoft/llvm-mctoll/blob/master/ExternalFunctions.h)

**Comment by leibo-hust** [comment]
> > > > ok, got it, so it means that I can add the functions that I want by myself?
> > > 
> > > 
> > > Yes.
> > 
> > 
> > that's really great!! and are there any guide on how to add the functions?thanks a lot
> 
> Take a look at the existing array entries and `struct RetAndArgs_t` in [ExternalFunctions.h](https://github.com/microsoft/llvm-mctoll/blob/master/ExternalFunctions.h)

OK, thanks a lot!

**Comment by leibo-hust** [comment]
Hi, I met a problem when I use the `round` funcion which in the [ExternalFunctions.cpp](https://github.com/microsoft/llvm-mctoll/blob/master/ExternalFunctions.cpp), but it didn't work too.
the source code is:

```
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
int main()
{
        float i = round(2.2);
        printf("The round of 2.2 is %f\n", i);
        return 0;
}
```
the round.txt that I defined is: 
```
;include `float round(float)` defined in round.out
include-functions {
  round.out:float round(float)
}
```
and the command that I used is:  `llvm-mctoll -d --filter-functions-file=round.txt round.out`
the problem is I can generate the rand.out-dis.ll, but its content is: 
```
; ModuleID = 'round.out'
source_filename = "round.out"
```
so, what's problem?

**Comment by bharadwajy** [comment]
As noted in #70, support for SSE2 registers and instruction is not yet supported. Consequently, support for handling `float` and `double` arguments is also not yet supported.

Also refer to https://github.com/microsoft/llvm-mctoll/issues/72#issuecomment-628848847 for the reason for why using `--filte-functions-file` is not the right address the issue at hand.

**Comment by leibo-hust** [comment]
Thanks a lot, I trie the `time` function without the `--filte-functions-file` option and I I succeeded!!! 

I reviewed the instructions related to the file `--filte-functions-file` option, I think I made a mistake before, this option is means to raise specific functions but not the full binary, right?

**Comment by leibo-hust** [comment]
@bharadwajy Hi, how long will it take for llvm-mctoll to support float types(SSE2 registers and instruction)? I compared many different tools and found that llvm-mctoll is the easiest to use and produces more concise results. So I want to use it as an analysis tool, thank you very much.

**Comment by bharadwajy** [comment]
> @bharadwajy Hi, how long will it take for llvm-mctoll to support float types(SSE2 registers and instruction)? I compared many different tools and found that llvm-mctoll is the easiest to use and produces more concise results. So I want to use it as an analysis tool, thank you very much.

@leibo-hust Thanks for your continued interest in llvm-mctoll. Much appreciated. While development continues on enhancing various capabilities of llvm-mctoll - of which support to abstract SSE2 registers and instructions has a higher priority - it is difficult for me to provide a time line at this time. 

As always, any/all help, if it can be offered, is highly appreciated.

**Comment by leibo-hust** [comment]
Thank you very much, I will continue to follow `llvm-mctoll`. I will do my best to provide some information, thanks again!
