### ISSUE TITLE
Lifting a binary that uses SO library  

### ISSUE THREAD

**Issue by ppashakhanloo** [microsoft/llvm-mctoll#73]
I have an ELF executable that was previously compiled with -lm to use the standard math SO file.
I am trying to lift this executable to LLVM IR. However, I get the following error, and the IR is not generated.

Unsupported undefined function
...
Aborted (core dumped)

**Comment by bharadwajy** [comment]
Thanks for your report.

It appears that the prototypes of math library functions that were linked to your executable are not known to the tool. The tool would print the function above the line `Unsupported undefined function`. You can lookup the prototype of that function and add it to [ExternalFunctions.cpp](https://github.com/microsoft/llvm-mctoll/blob/master/ExternalFunctions.cpp) as I suggested in #72.

**Comment by bharadwajy** [comment]
No follow up from the reporter. 

Please reopen as needed.
