### ISSUE TITLE
Comparision to mcsema?

### ISSUE THREAD

**Issue by bennofs** [microsoft/llvm-mctoll#76]
Hey, I just discovered this project, and was wondering how it compares to https://github.com/lifting-bits/mcsema? mcsema seems to be much older, and is also a binary-to-llvm-bitcode lifter.

**Comment by bharadwajy** [comment]
Thanks for your interest in `llvm-mctoll`. One of the primary goals of this project is to build a binary raiser/lifter to LLVM IR, solely using (as much as possible) LLVM infrastructure and generate LLVM IR that is as architecture-independent as possible. 

I have not had a chance to compare and contrast `llvm-mctoll` with other similar tools, although I did see a one or two instances on the web that do that. 

Yes, this is a relatively young project that is slowly working towards supporting abstraction of various ISA-specific data and control flow represented in a binary. Any interest and potential help is highly appreciated.

FWIW, `llvm-mctoll` does have a command-line option to emit bit code. However, the default output is text form. Of course, as you might know, one can generate bitcode from text form using `llvm-as`.
