### ISSUE TITLE
Failed to build mctoll with cmpilation errors

### ISSUE THREAD

**Issue by stephan-yichao-zhao** [microsoft/llvm-mctoll#77]
The errors are like

/home/./llvm-project/llvm/tools/llvm-mctoll/llvm-mctoll.cpp:1532:61: error: member reference type 'const llvm::object::ELFFile<llvm::object::ELFType<llvm::support::little, true> >::Elf_Ehdr' (aka 'const Elf_Ehdr_Impl<ELFType<(llvm::support::endianness)1U, true> >') is not a pointer; did you mean to use '.'?
      auto EType = Elf64LEObjFile->getELFFile()->getHeader()->e_type;
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~

/home/./llvm-project/llvm/tools/llvm-mctoll/X86/X86MachineInstructionRaiserUtils.cpp:429:57: error: member reference type 'const llvm::object::ELFFile<llvm::object::ELFType<llvm::support::little, true> >::Elf_Ehdr' (aka 'const Elf_Ehdr_Impl<ELFType<(llvm::support::endianness)1U, true> >') is not a pointer; did you mean to use '.'?
  auto EType = Elf64LEObjFile->getELFFile()->getHeader()->e_type;
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~

/home/./llvm-project/llvm/tools/llvm-mctoll/X86/X86MachineInstructionRaiserUtils.cpp:1109:69: error: member reference type 'const llvm::object::ELFFile<llvm::object::ELFType<llvm::support::little, true> >::Elf_Ehdr' (aka 'const Elf_Ehdr_Impl<ELFType<(llvm::support::endianness)1U, true> >') is not a pointer; did you mean to use '.'?
  unsigned char ExecType = Elf64LEObjFile->getELFFile()->getHeader()->e_type;
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~

**Comment by bharadwajy** [comment]
Thanks for your bug report.

Can you provide the following information to help with reproducing the failure?

1. Version of Linux distribution.
2. Commit id of the llvm-project used to build (Note that the current tip of llvm-mctoll is expected to build using llvm-project tip with commit id listed in [LLVMVersion.txt](https://github.com/microsoft/llvm-mctoll/blob/master/LLVMVersion.txt).
3. Full command line used to configure llvm.
4. Build command (such as make or ninja <target>.

Please provide any additional information that you think might be helpful to reproduce the reported build failure.

**Comment by stephan-yichao-zhao** [comment]
I missed the step "git checkout <hash>". After checking out the correct version, it got compiled.
