### ISSUE TITLE
Running llvm-mctoll on macOS

### ISSUE THREAD

**Issue by martin-fink** [microsoft/llvm-mctoll#85]
Hi, I'm trying to run this tool on macOS to lift x86_64 Linux binaries. For this, I need to include the Linux headers with the functions the program calls, such as stdio.h, stdlib.h, etc.

I tried copying over `/usr/include` from a Linux machine and running
```bash
llvm-mctoll --include-files=./include/stdlib.h,./include/stdlib.h
```
This leads to the problem that these header files include other headers, e.g.  `#include <getopts.h>`:
```
/my/current/dir/include/getopt.h:24:10: error: 'features.h' file not found with <angled> include; use "quotes" instead
#include <features.h>
         ^~~~~~~~~~~~
         "features.h"
```

 How can I tell mctoll that `./include` is the root include directory? clang has a `-iwithsysroot` flag, but it doesn't seem like mctoll supports anything like that.

I looked through the code and it seems like `ExternalFunctions::getUserSpecifiedFuncPrototypes` is the function where the headers are parsed with clang's subcommand `parse-header-files`. Do you know if I can somehow pass something like `-iwithsysroot` to `parse-header-files` here or in some other place in the code?

Thanks 🙂

**Comment by bharadwajy** [comment]
You should be able to create a JSON compilation database file or a simple `compile_flags.txt` as outlined [here](https://clang.llvm.org/docs/JSONCompilationDatabase.html). That file name can be passed to `llvm-mctoll` using the command-line argument `--compilation-db-path=/path/to/file`.

This should provide you with the full ability to pass any compiler flags you desire to be honored while parsing the files specified in `--include-files` option of llvm-mctoll.

Hope that helps.

Thanks for your interest in the tool!

**Comment by martin-fink** [comment]
Awesome, thanks @bharadwajy! Helped me a lot.

I created the following `compile_flags.txt`:

```
-isystem
/my/current/dir/include
-iwithsysroot
/my/current/dir/include/x86_64-linux-gnu
```

Thanks again! 🙂
